### ISSUE TITLE
Randomly stops

### ISSUE THREAD

**Issue by skpy** [tmate-io/tmate-ssh-server#22]
We're running tmate-slave on RHEL7.  About once a week, but not consistently, the daemon stops accepting new requests.  systemd reports that the process is still running.

If there's some easy way for us to monitor the service and restart it as needed, that would be fine; but we're not seeing any easy way to accomplish that.

Is there anything specific we can look for on the tmate-slave server itself to confirm that the process is working as expected?  Or, is there something we can look for to confirm that a problem as occurred?

**Comment by nviennot** [comment]
Have you tried running the latest version from the master branch? I fixed a bug that address that exact issue recently
