### ISSUE TITLE
msgpack & libevent not found

### ISSUE THREAD

**Issue by becste** [tmate-io/tmate-ssh-server#29]
In centos 7 ./configure wont proceed as msgpack is not found. Further looking into the output
`checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking whether gcc and cc understand -c and -o together... yes
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for pkg-config... /bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for glibc... yes
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking bitstring.h usability... no
checking bitstring.h presence... no
checking for bitstring.h... no
checking curses.h usability... yes
checking curses.h presence... yes
checking for curses.h... yes
checking dirent.h usability... yes
checking dirent.h presence... yes
checking for dirent.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking for inttypes.h... (cached) yes
checking libutil.h usability... no
checking libutil.h presence... no
checking for libutil.h... no
checking ncurses.h usability... yes
checking ncurses.h presence... yes
checking for ncurses.h... yes
checking ndir.h usability... no
checking ndir.h presence... no
checking for ndir.h... no
checking paths.h usability... yes
checking paths.h presence... yes
checking for paths.h... yes
checking pty.h usability... yes
checking pty.h presence... yes
checking for pty.h... yes
checking for stdint.h... (cached) yes
checking sys/dir.h usability... yes
checking sys/dir.h presence... yes
checking for sys/dir.h... yes
checking sys/ndir.h usability... no
checking sys/ndir.h presence... no
checking for sys/ndir.h... no
checking sys/tree.h usability... no
checking sys/tree.h presence... no
checking for sys/tree.h... no
checking term.h usability... yes
checking term.h presence... yes
checking for term.h... yes
checking util.h usability... no
checking util.h presence... no
checking for util.h... no
checking for library containing flock... none required
checking for dirfd... yes
checking for flock... yes
checking for setproctitle... no
checking for sysconf... yes
checking for cfmakeraw... yes
checking for library containing clock_gettime... none required
checking for LIBEVENT... no
checking for library containing event_init... -levent
checking for LIBNCURSES... yes
checking utempter.h usability... no
checking utempter.h presence... no
checking for utempter.h... no
checking for MSGPACK... no
configure: error: "msgpack >= 1.2.0 not found"` also shows that libevent is not found even though it is present. I have checked the various folders containing msgpack and all is present. Also installing the msgpack from yum (then version 1.4) does not help.

On Ubuntu it is fine. I have followed already all the other guides and possible resolutions mentioned before so any help is really appreciated.

**Comment by dmd** [comment]
I get the same on Ubuntu 14.04.5 LTS

**Comment by aldou** [comment]
On ubuntu: 
apt install libmsgpack-dev

**Comment by sputnick-dev** [comment]
On a Debian distro : (`apt install libmsgpack-dev` DONE)
```
# cat /etc/debian_version 
8.11
# ./configure
[...] 
checking for library containing utempter_add_record... -lutempter
checking for MSGPACK... no
configure: error: "msgpack >= 1.2.0 not found"
```

**Comment by nviennot** [comment]
Maybe it's easier to use the docker image at: https://hub.docker.com/r/tmate/tmate-ssh-server
