### ISSUE TITLE
Avoid 1, l, I aswell as O and 0 inside the tmate-id

### ISSUE THREAD

**Issue by linuxundich** [tmate-io/tmate-ssh-server#31]
I use Tmate from time to time to help other linux users, when the Xserver on their computer fails. In this case it's quite complicated to copy and paste the id into an email, so I need to "transmit" the id by speaking on the phone or asking to capture the tmate screen with the id with a smartphone, so that they can send me a "screenshot". 

The problem: The Tmate-id contains letters like "1", "l" (small L) and "I" (capital i) aswell as O (capital ohhh) and "0" (zero). Depending on the terminal font it's quite complicated to decipher the correct id and it takes a couple of tries to establish the connection. So my wish: Avoid those characters inside the id completely.

**Comment by nviennot** [comment]
Done!
