### ISSUE TITLE
Cannot connect to server (fatal: Error polling ssh socket: Socket error: disconnected)

### ISSUE THREAD

**Issue by fujisan43** [tmate-io/tmate-ssh-server#34]
I started a tmate server like this:
`sudo ./tmate-slave -s -v -p 224 -k /etc/ssh/ &`

and my `.tmate.conf` looks like this:
```
set -g tmate-server-host "myserver.mydomain"
set -g tmate-server-port 224
set -g tmate-server-rsa-fingerprint   "fcEujDgGDPFdkA27hDah9IjLOctnToTyZfgjc3pmRtQ"
set -g tmate-server-ecdsa-fingerprint "VQ5TFd3fKHWlMRy0rQmkky6FFzvYgOcV7pgyQI5iIY"
```
When I start tmate on the client, I get:
```
[tmate] Reconnecting... (Cannot authenticate server)                                                                                                                                                                                          
[tmate] myserver.mydomain lookup failure. Retrying in 2 seconds (nodename nor servname provided, or not known)                                                                                                                                     
```
I get the following messages on the server side in `/var/log/messages`:

```
Feb 23 12:15:59 myserver tmate-remote-tmux[32376]: (tmate) Accepting connections on :224
Feb 23 12:17:19 myserver tmate-remote-tmux[32376]: (tmate) Child spawned pid=32505, ip=10.0.21.200
Feb 23 12:17:19 myserver tmate-remote-tmux[32505]: [init] (tmate) Bootstrapping ssh client ip=10.0.21.200
Feb 23 12:17:19 myserver tmate-remote-tmux[32505]: [init] (tmate) Exchanging DH keys
Feb 23 12:17:19 myserver tmate-remote-tmux[32505]: [init] (tmate) fatal: Error polling ssh socket: Socket error: disconnected
Feb 23 12:17:23 myserver tmate-remote-tmux[32376]: (tmate) Child spawned pid=32506, ip=10.0.21.200
Feb 23 12:17:23 myserver tmate-remote-tmux[32506]: [init] (tmate) Bootstrapping ssh client ip=10.0.21.200
Feb 23 12:17:23 myserver tmate-remote-tmux[32506]: [init] (tmate) Exchanging DH keys
Feb 23 12:17:23 myserver tmate-remote-tmux[32506]: [init] (tmate) fatal: Error polling ssh socket: Socket error: disconnected
Feb 23 12:17:27 myserver tmate-remote-tmux[32376]: (tmate) Child spawned pid=32507, ip=10.0.21.200
Feb 23 12:17:27 myserver tmate-remote-tmux[32507]: [init] (tmate) Bootstrapping ssh client ip=10.0.21.200
Feb 23 12:17:27 myserver tmate-remote-tmux[32507]: [init] (tmate) Exchanging DH keys
Feb 23 12:17:27 myserver tmate-remote-tmux[32507]: [init] (tmate) fatal: Error polling ssh socket: Socket error: disconnected
```
What should I do?
F.

**Comment by adgud** [comment]
I have the same exact error and have absolutely no idea how to fix it. Running Fedora 25.

**Comment by virtualguard** [comment]
Same Issue on Ubuntu 16.04 any idea how to fix ??

**Comment by lkthomas** [comment]
same problem here on Ubuntu 16.04, what's the fix?

**Comment by gustavoip** [comment]
Same issue on Ubuntu 17.04.

**Comment by ddnomad** [comment]
I've encountered the same issue. Can we have a word from @nviennot or @nicm please?

**Comment by nviennot** [comment]
I have limited availability to work on tmate. The project is open-source, please poke at the issue, help each other out!

**Comment by rbuzatu90** [comment]
I think all of us would try to fix it but we lack the knowledge to do so :(

**Comment by Ricky54326** [comment]
Hello friends!

I just spent a few hours tracking down the same issue, and here's what it is:

In your ~/.tmate.conf file on the client, you need to make sure you're specifying the MD5 fingerprint of both of your keys (ECDSA & RSA). If you specify the SHA256/512 version, it will give this error.

To get that fingerprint: 
`ssh-keygen -E md5 -lf <file_name>`

Here's my entire ~/.tmate.conf that works fine from a fresh build (I redacted the fingerprints, but they have to be in this MD5-style, colon-delimited format for this to work): 

```
set -g tmate-server-host "localhost"
set -g tmate-server-port 23
set -g tmate-server-rsa-fingerprint   "aa:bb:cc"
set -g tmate-server-ecdsa-fingerprint "aa:bb:cc"
#set -g tmate-identity ""              # Can be specified to use a different SSH key.
```

I think we could do some better error handling in the code itself to throw slightly less crappy errors, but this might be a `libssh` limitation. 

Cheers! 
@ddnomad @rbuzatu90 @nviennot

**Comment by Wangbin-Sun** [comment]
> Hello friends!
> 
> I just spent a few hours tracking down the same issue, and here's what it is:
> 
> In your ~/.tmate.conf file on the client, you need to make sure you're specifying the MD5 fingerprint of both of your keys (ECDSA & RSA). If you specify the SHA256/512 version, it will give this error.
> 
> To get that fingerprint:
> `ssh-keygen -E md5 -lf <file_name>`
> 
> i.e.:
> 
> ```
> $ ssh-keygen -E md5 -lf keys/ssh_host_rsa_key.pub
> 2048 MD5:ab:cd:ef:ab:cd:ef:ab:cd:ef:ab:cd:ef 
> ```
> 
> Here's my entire ~/.tmate.conf that works fine from a fresh build (I redacted the fingerprints, but they have to be in this MD5-style, colon-delimited format for this to work):
> 
> ```
> set -g tmate-server-host "localhost"
> set -g tmate-server-port 23
> set -g tmate-server-rsa-fingerprint   "aa:bb:cc"
> set -g tmate-server-ecdsa-fingerprint "aa:bb:cc"
> #set -g tmate-identity ""              # Can be specified to use a different SSH key.
> ```
> 
> I think we could do some better error handling in the code itself to throw slightly less crappy errors, but this might be a `libssh` limitation.
> 
> Cheers!
> @ddnomad @rbuzatu90 @nviennot

Great, it work!
Besides, I delete the key related to ed25519 in /keys

**Comment by nviennot** [comment]
In production, I only use the RSA keys, because older clients are not happy with the new keys.

**Comment by nviennot** [comment]
https://github.com/tmate-io/tmate/commit/cbec43f56dfb48c2fb6e00faa2cb85443d4b7d8f should make it easier to debug these kind of errors
