### ISSUE TITLE
Setup CI with dockerhub

### ISSUE THREAD

**Issue by cgetzen** [tmate-io/tmate-ssh-server#55]
Containers fail to build on a few of the most recent commits to master. It would be great to catch these failures earlier. It looks like the failures relate to https://github.com/tmate-io/tmate-slave/issues/52.

**Comment by nviennot** [comment]
I'm not keeping some docker images up to date: https://hub.docker.com/r/tmate/tmate-ssh-server

There are in used for the tmate.io services
