### ISSUE TITLE
ships a copy of the tmux source code

### ISSUE THREAD

**Issue by anarcat** [tmate-io/tmate-ssh-server#59]
is there any reason why this ships an entire copy of the tmux source code? I haven't checked in details, but it sure looks like at least `cmd.c` comes from tmux... 

This is a problem when packaging this in Debian: we try to avoid such duplicate copies of code to make it easier to deal with security issues...

**Comment by nviennot** [comment]
tmate is a fork of tmux, so it shares many of the same sources. However, many original tmux sources were modified. The code is not a duplicate. I hope this clarifies.

**Comment by anarcat** [comment]
> tmate is a fork of tmux, so it shares many of the same sources. However, many original tmux sources were modified. The code is not a duplicate. I hope this clarifies.

Well, I guess I understand that. What I'm puzzled about is *why* this was done that way and why the changes aren't being merged back upstream to resolve the fork. :)

**Comment by nviennot** [comment]
The reason it was done that was to avoid having to tunnel the client connection to the person hosting the tmate session. In other words, SSH sessions are rendered on the tmate-ssh-server side.

The data moving from the host to the tmate-ssh-server is roughly the content of each panes.

A while ago, I wrote a draft paper for tmate: https://viennot.com/tmate.pdf there might be clues of why certain things are the way they are.

**Comment by anarcat** [comment]
is there any possibility of the fork being resolved?

how do you make sure that updates on tmux migrate back into the server?

thanks for your response and your work, by the way... i don't want to
pick on you or anything, but this is the kind of stuff that's
problematic if we want to package this for debian...

**Comment by nviennot** [comment]
The fork will not be resolved. I backport their branch onto tmate. It's a bit of a pain.

I understand

**Comment by nviennot** [comment]
tmate3 will most likely decouple itself from tmux. So it will eventually be solved.
