### ISSUE TITLE
tmate web connection though tmate-ssh-server

### ISSUE THREAD

**Issue by markbajaj** [tmate-io/tmate-ssh-server#60]
Hi,

I was wondering if I was missing something. I have got the tmate-ssh-server working on a Centos 7 LXC, it works fine for ssh connections, but I can't seem to get it to generate a web URL. Is this possible with the self-hosted server? Do I need apache installed on my server?

I have looked through all the issues and can't seem to see any mention of this. 

It may be intended behaviour?

Thanks in advance

mb

**Comment by nviennot** [comment]
You'd have to use https://github.com/tmate-io/tmate-master and https://github.com/tmate-io/tmate-proxy and connect the ssh-server to the proxy with the -x CLI option.
There's no documentation at the moment, I'm sorry
