### ISSUE TITLE
Example docker-compose.yml file

### ISSUE THREAD

**Issue by expelledboy** [tmate-io/tmate-ssh-server#63]
Hi, I cant get the docker image working at https://hub.docker.com/r/tmate/tmate-ssh-server

Could someone please add a `docker-compose.yml` file which works?

**Comment by nviennot** [comment]
I made some config for the dev env. Install [Tilt](https://docs.tilt.dev/)
and then run `tilt up` in this folder: https://github.com/tmate-io/tmate-kube/tree/master/dev

**Comment by expelledboy** [comment]
Wow tilt does look cool, but are you telling me you can run kube on your laptop without it sounding like its about to take off on a long haul flight to Easter island? 😂

I am running a single node docker server atm. Was planning on migrating, but just havent had the chance yet.

**Comment by nviennot** [comment]
kube will definitely keep me warm in the winter :)

**Comment by ictus4u** [comment]
I  just found both this question and [this repo](https://github.com/kkoralsky/tmate-docker-compose) that probably could be an answer.
