### ISSUE TITLE
Cannot start server docker "host key file must be set"

### ISSUE THREAD

**Issue by starlilyth** [tmate-io/tmate-ssh-server#69]
I am attempting to use the tmate-ssh-server docker container from https://hub.docker.com/r/tmate/tmate-ssh-server
I have generated the keys as instructed, but no matter how try to pass the keys directory the container fails to start with: `fatal: Error listening to socket: ECDSA, ED25519, DSA, or RSA host key file must be set\n`

```
ls -l ./keys
-rw-------. 1 root root  419 Jan 14 02:18 ssh_host_ed25519_key
-rw-r--r--. 1 root root  106 Jan 14 02:18 ssh_host_ed25519_key.pub
-rw-------. 1 root root 1679 Jan 14 02:18 ssh_host_rsa_key
-rw-r--r--. 1 root root  406 Jan 14 02:18 ssh_host_rsa_key.pub
```

Command variations tried: 
```
docker run -e SSH_KEYS_PATH='./keys' tmate/tmate-ssh-server
docker run tmate/tmate-ssh-server SSH_KEYS_PATH='./keys'
```

**Comment by nviennot** [comment]
I suspect the `keys` directory you have is on the host machine, and not in your container. Could that be the case?

You would have to configure docker to mount a volume directory (with `--volume`) to expose the keys folder in the container. Alternatively you can create a new container with a DockerFile, and create that keys folder.

**Comment by starlilyth** [comment]
Yes thats correct. I am new to docker, sorry for misunderstanding. 
What is the expected/preferred way to add the keys to the container?

**Comment by starlilyth** [comment]
By using the -v flag I can now get the image to load the keys, but I still get the same error: 
```
docker run -v /root/tmate/keys:/etc/tmate/keys -e SSH_KEYS_PATH='/etc/tmate/keys' --rm tmate/tmate-ssh-server
Loading key /etc/tmate/keys/ssh_host_rsa_key
Loading key /etc/tmate/keys/ssh_host_ed25519_key
fatal: Error listening to socket: ECDSA, ED25519, DSA, or RSA host key file must be set\n
```

**Comment by starlilyth** [comment]
Ah hah! I have it working with the above command. Thank you!

**Comment by Bettehem** [comment]
> By using the -v flag I can now get the image to load the keys, but I still get the same error:
> 
> ```
> docker run -v /etc/tmate/keys:/etc/tmate/keys -e SSH_KEYS_PATH='/etc/tmate/keys' --rm tmate/tmate-ssh-server
> Loading key /etc/tmate/keys/ssh_host_rsa_key
> Loading key /etc/tmate/keys/ssh_host_ed25519_key
> fatal: Error listening to socket: ECDSA, ED25519, DSA, or RSA host key file must be set\n
> ```

I'm facing the same exact issue.


> Ah hah! I have it working with the above command. Thank you!

Could you please tell me the command which you used to get it working?
